### ISSUE TITLE
Strange warning for zipped csv resources

### ISSUE THREAD

**Issue by morty** [datagovuk/ckanext-dgu#172]
![csv-zip](https://cloud.githubusercontent.com/assets/3272/10147977/edecbc66-6628-11e5-8831-579ee6c55de3.png)

Why is the detected format CSV?

**Comment by morty** [comment]
It also seems that CSV is the format used in deciding the Content-Type to serve this resource. See #170.

**Comment by davidread** [comment]
Originally I got QA to say a zipped CSV was format "CSV / Zip", but actually the Zip part doesn't make a lot of difference to most users. It's one extra click when you download on Windows. And when you look at the facets in search, if you're looking for a CSV, you really don't care if it is zipped. So that's why I dropped the Zip in the format.

However clearly there is a use for knowing it is zipped here. Maybe we should get QA to add a separate flag to say it is zipped so that we can select a better Content-Type on download?

**Comment by davidread** [comment]
And we should probably do some tidying of what people set their format field to, so we lose this warning.

**Comment by davidread** [comment]
The package create/edit form has since been changed to have 'CSV' in the format dropdown and not 'CSV / Zip'.

The other job here is to change datasets with format='CSV / Zip' to format='CSV'. This is covered by #386.

So closing this ticket.
