### ISSUE TITLE
ckanext-issues test failures

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#186]

**Comment by rossjones** [comment]
This appears to be that when you select the number of items per page to show in results, it loses the ordering and defaults to newest... which is bad.

**Comment by rossjones** [comment]
e02ffd9 fixes test failures due to templates

When changing the number of items to show per page, the current sort
order was lost.

When clicking next, the current sort order AND the number of items per
page was lost.

Also fixed the assertions that were failing because of ascii encoding
issues.

Will also make sure these issues do not appear in our templates.

**Comment by davidread** [comment]
Done
