### ISSUE TITLE
Time series form bug

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#275]
From James:

    I've changed the dataset below into a time-series, but its acting weird:
    https://data.gov.uk/dataset/financial-transactions-spend-data-bis
    
    4 of the data resources have been moved out of the time-series and won't go back in.

**Comment by rossjones** [comment]
Once a dataset gets in this state, with mostly timeseries, and some individual resources it is no longer editable because validation stops you using two different resource types.

Reseting to single entries, and then back to timeseries, it isn't straight-forward to replicate.

**Comment by rossjones** [comment]
I can't replicate this, but I have written a tool to fix the situation.

Once a dataset gets in this state, trying to save it will cause problems as they don't show up in the time-series editor, and then cause a validation error (because it has both resource types).

I've been unable to find out why this happened, and presumably nothing strange happened during the editing?  I think this is a positive reason for having bug-reports direct from the person who experienced it.

When going to the edit form, if we have time-series resources, then any individual_resources should be added to the bottom of the form. This will cause a validation error as the date field will be empty for these resources.  But this is better than having hidden resources that stop you from editing.

**Comment by davidread** [comment]
> any individual_resources should be added to the bottom of the form

I just tried this on https://data.gov.uk/dataset/edit/financial-transactions-spend-data-bis#tab-data and it doesn't seem to be the case. Is this a PR you are preparing or haven't deployed yet?

**Comment by davidread** [comment]
Ah, i just read you again - "should" as in a proposal, not something done. Sounds good!

**Comment by rossjones** [comment]
Adding the individual_resources in the timeseries table is straight-forward, in most cases the list will be empty, but when it isn't, it fills them in waiting for a date.

However because the individual_resources are not [], the table is rendered with the data (but hidden) and causes a validation error.

**Comment by rossjones** [comment]
This has been solved by some template-magic, and needs review.

**Comment by davidread** [comment]
The workaround #292 is great, but I think I've recreated the problem now.

1. Create a dataset with two normal resources.
2. Edit it, change it to timeseries and add a date to both resources, and edit the description of the first resource only.
3. Save it and notice that the 2nd resource has not had the date attached.

There seems to be something in the resource saving stuff that only saves the resource if it has changed. However it ignores the date column. So if only the date has changed it doesn't save it.

**Comment by davidread** [comment]
Found the fix on master https://github.com/ckan/ckan/issues/2158

**Comment by davidread** [comment]
All deployed and BIS dataset saved ok.
