### ISSUE TITLE
Re-enable use of '-' in Solr

### ISSUE THREAD

**Issue by rossjones** [datagovuk/ckanext-dgu#306]

**Comment by davidread** [comment]
To do this there is a thing called 'solr_escape' which we can easily remove.

We talked about warning the user for the circumstance when he searches for "LIDAR Composite DSM - 1m" and he still wants to get that. Maybe the clue is that there is a space between the dash and the next thing and in that circumstance we could quote the dash (assuming that works)? (I believe that is what google does, comparing searching for "fish - rod" and "fish -rod").

Otherwise I was wondering about explaining to the user in the search results something like 'NB search excludes term: "1m"' or some sort of parsed version of the search string. I have a feeling that SOLR returns a bit of info on this. Or maybe there is a library that does this. But maybe that is overboard.
