### ISSUE TITLE
Incorrect dBase data format detected for zipped shapefile

### ISSUE THREAD

**Issue by sumothecat** [datagovuk/ckanext-dgu#350]
We've released some spatial datasets in the proprietary Esri Shapefile format. The files are .zip files of the shapefile directory. However the detected format is dBase.

https://data.gov.uk/dataset/at-sea-densities-of-shag-in-the-breeding-season/resource/034894be-637d-4a8c-a2c3-adbe7be07332 l

Also in the openess rating tooltip, 'Content of file appeared to be dBase'.

The Gemini DataFormat field has 'ESRI Arc/View ShapeFile'.
https://data.gov.uk/api/2/rest/harvestobject/ac4646db-5716-4015-8ba2-9a2e30e419d7/xml 

Instead of dBase the detected format of a zip should perhaps be "unknown", and then you could present the Data Format string, if given, as the (claimed) format?

**Comment by davidread** [comment]
Thanks for flagging this. I've improved the detection, so the dBase file in the zip doesn't throw it off scent any more and it detects it as Shapefile now.

Gemini/ISO19139 is not much help in most cases tbh because it has a list of formats and a list of resource locator URLs, and doesn't say which goes with which (!)
