### ISSUE TITLE
Organogram data migration

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#365]
This was originally about testing the viz - a sample of existing records.
It has become about the data migration.

**Comment by davidread** [comment]
I'm recording the tests and issues as I go along in this sheet: https://docs.google.com/spreadsheets/d/16nmt30fa3_PKdjWCM88KPMB0Vmvlwc3RoHjhg1Xqu_U/edit#gid=0

**Comment by davidread** [comment]
@ratajczak I can't see any of the organogram data showing up on the manage screens so I can't continue the testing of organogram preview - can you do a load asap?

e.g. https://test.data.gov.uk/organogram/manage/advisory-conciliation-and-arbitration-service

**Comment by ratajczak** [comment]
I just cleaned up organograms in Drupal and organogram datasets in CKAN (by removing resources) and wanted to re-run mass import but publishing now fails because CKAN responds with "409 Conflict" when I'm trying to attach the same CSV files to the same datasets.

For example if I try to publish 31 Mar 2011 organogram here:
https://test.data.gov.uk/organogram/manage/appointments-commission

I'm sending this json:
{"package_id":"7755f31f-f023-405a-9454-55cf30741aee","date":"31-03-2011","url":"https:\/\/test.data.gov.uk\/sites\/default\/files\/organogram\/appointments-commission\/31-03-2011\/appointments_commission-2011-03-31-organogram-junior.csv","format":"CSV","description":"Organogram - Junior CSV data"}

to

https://test.data.gov.uk/api/action/resource_create

and get 409

Shall we sync CKAN database with production to remove organogram datasets in CKAN and re-run mass upload?

**Comment by ratajczak** [comment]
I've later disable publishing part in my scrip and re-uploaded all organograms, so they are now ready to for testing in Drupal.
Here is the output from the script:

[organogram-upload-20160617-1400.txt](https://github.com/datagovuk/ckanext-dgu/files/322472/organogram-upload-20160617-1400.txt)

There are few (repeated) validation errors which look easy to fix (in etl script)

**Comment by davidread** [comment]
I've redone the tests and updated the spreadsheet.

I'll look at the text output and see if I can get them all to output what we had before.

**Comment by davidread** [comment]
I've emailed you, Pawel, about the errors, so that you can have another crack at this.

**Comment by davidread** [comment]
These are the errors I emailed about, and I'll update as they are fixed:

* [x] Missing top post - Pawel identified it as recursion issue - fixed 2nd August
* [x] XLS file upload failed ERROR: Expected numeric values in column "Payscale Minimum (£)" (or
N/A or N/D), but got text="ns". - David fixed 1st Aug
* [x] Publisher not found - Pawel fixed 9th Aug (DR has not tested yet)
* [x] XLS file upload failed ERROR: Could not find a senior post with "Reports to Senior Post"
value of "XX" (i.e. the top role) - David says this is fine to fail on
* [ ] XLS file upload failed ERROR: No sheet named <'(final data) junior-staff'>

**Comment by davidread** [comment]
New error seen on import 20th Aug:

* [ ] eadsheet contains errors: ERROR: File size is 0 bytes - for data/dgu/xls/student_loans_company-31-03-2015.xls

**Comment by davidread** [comment]
> XLS file upload failed ERROR: No sheet named <'(final data) junior-staff'>

Pawel said in email 16 Aug "I checked this last error and it works with a XLS file from the tripplestore." so hopefully this should be gone on the next run.

>  eadsheet contains errors: ERROR: File size is 0 bytes - for data/dgu/xls/student_loans_company-31-03-2015.xls

I've supplied an alternative XLS in the data/dgu/xls-from-triplestore dir now, so this problem should disappear on the next run.

**Comment by davidread** [comment]
@ratajczak do let me know the errors from the latest run, thanks

**Comment by davidread** [comment]
@ratajczak what are the upload errors in the latest run?

**Comment by ratajczak** [comment]
There were only 3 errors.

Two similar issues caused by these xls fles:
https://test.data.gov.uk/sites/default/files/organogram/uploads/infrastructure_planning_commission-2011-03-31-organogram.xls
https://test.data.gov.uk/sites/default/files/organogram/uploads/scottish_law_commission-2011-03-31-organogram.xls

These graphs don't render because there are no XX top posts in above XLS files:
https://test.data.gov.uk/organogram/infrastructure-planning-commission/2011-03-31
https://test.data.gov.uk/organogram/scottish-law-commission/2011-03-31

And the last error is previousely known empty xls (0 bytes) file for:
http://test.data.gov.uk/organogram/manage/student-loans-company-limited
for period 31-03-2015

**Comment by davidread** [comment]
"no XX top posts" - we've agreed these are fine to ignore.

"File size is 0 bytes" - this error has now gone from this weekend's upload.

This upload threw up 3 new concerns:

* "XLS file already uploaded" - I have just put in a fix for these duplicates, so it should go next time.

* 1405 http://test.data.gov.uk/organogram/manage/maritime-and-coastguard-agency [30-09-2015] - This is a corrupt file. I'll take it off the list by next time.

* 258 Can't get publisher id for "Ofsted" - It's probably because we changed the title of this publisher very recently to be its acronym. Although the name/URL stays the long
version: https://data.gov.uk/publisher/office-for-standards-in-education-childrens-services-and-skills . Do we simply need to propagate the name change into Drupal?

**Comment by davidread** [comment]
> 1405 http://test.data.gov.uk/organogram/manage/maritime-and-coastguard-agency [30-09-2015]

This is now removed from tso_combined.csv.

**Comment by davidread** [comment]
Latest migration has no sign of "XLS file already uploaded" or corrupt files. Pawel is happy to do ofsted upload manually. All done!
