### ISSUE TITLE
remove linked data

### ISSUE THREAD

**Issue by pigspamster** [datagovuk/ckanext-dgu#419]

**Comment by ratajczak** [comment]
I've deployed this here:
https://test.data.gov.uk/archive
https://test.data.gov.uk/archive/linked-data

I've also added link to the Archive section to the footer menu.

**Comment by davidread** [comment]
To make this approach work I think we need:
* a link to get to https://test.data.gov.uk/archive
* a banner on the linked data page saying that it is archived
* a redirect from the old URL https://test.data.gov.uk/linked-data/ (so that you're not breaking search engine and other links to the page)

But tbh I struggle with describing this as as "archived", as it's not likely to be held there for a long time. It's more that we're telling people we're no longer updating it and we're simply avoiding breaking old links. Maybe we could simply take the Linked Data page off the nav and add a banner saying it will no longer be updated. In our blog post mentioning its demise we include a link to it for posterity.

**Comment by ratajczak** [comment]
I like this idea.
I'm assuming that we will do the same with glossary and there will be no need to create archive section at all.
Shall I revert what I did with archive and try this?

**Comment by davidread** [comment]
Sounds good

**Comment by ratajczak** [comment]
I've reverted what I've done previously and removed archive section.
Now linked data section is just removed from navigation and added a message about archiving on all linked data pages:
https://test.data.gov.uk/linked-data

**Comment by davidread** [comment]
Looks good to me. 

Message is fine. When we have a blog post we can add a link to that.

This is the model should apply to other pages we are archiving. Forums and glossary will also need some disabling of the interaction, and perhaps saving all the forum comments as a CSV too for posterity.

**Comment by davidread** [comment]
I've removed it from ckan nav too - branch 'archive-features'

**Comment by davidread** [comment]
AA has now decided this section of the site should be simply be deleted, not simply marked as archived. I'm fine with that.

So the URLs for the pages will become a 404.

Just noting the pages:
* https://test.data.gov.uk/linked-data
* https://test.data.gov.uk/linked-data/overview-of-linked-data
* https://test.data.gov.uk/linked-data/what-is-linked-data
* https://test.data.gov.uk/linked-data/list-linked-datasets-vocabularies

**Comment by ratajczak** [comment]
This is done on test server.

**Comment by davidread** [comment]
AA says now remove on live.

**Comment by ratajczak** [comment]
I deleted these pages and Linked data link from interact menu in Drupal, @davidread could you please remove this link from interact menu in CKAN?

**Comment by davidread** [comment]
This is done on the ckan side too now.

Hooray, this is complete!
