### ISSUE TITLE
Preview of different spreadsheet formats

### ISSUE THREAD

**Issue by zvetaM** [datagovuk/ckanext-dgu#468]
Hello,

in resource_read.html in /ckanext/dgu/theme/templates/package/read_common.html it states, that it supports preview of only CSV, free text and spreadsheets. I've uploaded an xlsx file, and it didn't show up. I've tried adding

```
{% block data_preview %}
{{ h.resource_preview(c.resource, c.package) }}
{% endblock %}
```

from _templates/package/resource_read.html_ in ckan 2.2 and it seems like it supports more preview options, but no xlsx. Is it sensible to combine both data preview from core CKAN and data preview from your datagovuk, or would it be better to add support for xlsx (as well as xml and others, if possible) to your datagovuk?

Thank you very much for your time!

Matevž

**Comment by davidread** [comment]
xlsx previews ok for us:

https://data.gov.uk/dataset/civil-service-people-survey-2014/resource/06897866-41c9-4db0-ac62-d39573ceefa3

So in principle it should work. That said, plenty of files cause the previewer problems.

If my memory serves correctly, this is how this works: Core CKAN's recline javascript calls to a data proxy service running on Google App Engine. DGU's javascript calls a local proxy service (read more here: https://github.com/datagovuk/ckanext-datapreview ). Both proxies convert the XLSX to a bit of JSON, so that is what does the hard work. The DGU one is a fork of the CKAN one, simply to make it run locally. Maybe there are useful things from the CKAN version that we can copy across to the fork?
