### ISSUE TITLE
Harvest validation errors

### ISSUE THREAD

**Issue by zvetaM** [datagovuk/ckanext-dgu#532]
Hello!

We are setting a Slovenian government portal, on which we will also have to harvest from http://prostor4.gov.si/imps/srv/slv/csw . But when I try to set up harvesting of gemini-csw, it fails with following errors: 

```
Harvest of GUID 616148d1-3de8-441d-9d23-129a4c1b29fe
    Error importing Gemini document
    ** ABORT! ** Import of this object is aborted because of errors associated with validation.
    Validating against "ISO19139 Table A.1 Constraints Schematron (Medin/Parslow 1.4)" profile failed:
    Error Message: The 'gmd:locale' element has no child elements.
    Error Location: /gmd:MD_Metadata/gmd:locale
```

I tried setting _ckanext.spatial.harvest.continue_on_validation_errors_ to _true_, but it still manages to harvest just around 30 out of 146 total datasets.

Since prostor4.gov.si is one of the main portals we will need to successfully harvest, and it aims to be compatible with www.europeandataportal.eu, I've had the idea that if I try substituting your ckanext-harvest and ckanext-spatial with upstream ckanext-harvest and ckanext-spatial from CKAN, and patch things up, harvest will proceed successfully. However, that turned out to be a bigger task than I first thought.

If it would be possible, I would like to ask, is there any other way to fix the validation errors above, and/or whether it is sensible or even possible to use upstream CKAN ckanext's in exchange of your forked ones in this particular case?

Thank you very much for your time,

Matevž Markovič

**Comment by davidread** [comment]
You probably want to use the [CSWHarvester](https://github.com/datagovuk/ckanext-spatial/blob/master/ckanext/spatial/harvesters/csw.py#L19) rather than the [GeminiCswHarvester](https://github.com/datagovuk/ckanext-spatial/blob/master/ckanext/spatial/harvesters/gemini.py#L538). Gemini is a UK standard which is similar to ISO19139 but a bit stricter in places, hence why you are getting errors for records that would be harvested fine by the European INSPIRE Geoportal.

I believe you can swap them by changing your ckan config file's ckan.plugins line to include cswserver instead of gemini_csw_harvester and restarting.

I suspect there may still be some issues with CSWHarvester and you may wish to copy harvesters/base.py and csw.py from https://github.com/ckan/ckanext-spatial . These files are not used by data.gov.uk, so if you update from that upstream repo, and confirm it works, then I'd very happily merge this change into this fork.

**Comment by davidread** [comment]
That being said, INSPIRE records are complex and there seems plenty of debate about how best to fill them in. So any mapping from the XML to CKAN is never going to be perfect and work for all variations. So do persevere with trying to understand the validation errors, and adjust the mapping if necessary.

**Comment by davidread** [comment]
You need to restart celery

**Comment by zvetaM** [comment]
If by restarting celery you mean restarting jobs that take care of queues, I manage them through supervisord, along with harvester_fetch_consumer and harvester_gather_consumer. I was restarting them after every change in the code.

Anyway, running harvester today, it produced totally different errors:
Harvest of GUID 10db1697-964f-4aa2-b646-5a690ab80501
System error (need more than 2 values to unpack)
Harvest of GUID 616148d1-3de8-441d-9d23-129a4c1b29fe
System error (need more than 2 values to unpack)
Harvest of GUID 1725fb3b-628f-40a8-a556-f9f3360d77ed
System error (need more than 2 values to unpack)
...

The funny thing is, almost all datasets passed validation (Validated against "GEMINI 2.1 Schematron 1.3"; Validation passed), only a couple of them failed with previous validation errors (such as Validation Error: Element 'gco:Date': '' is not a valid value of the union type 'gco:Date_Type'., line 64").

The full text of particular system errors above is

```
 [ckanext.harvest.model] System error (need more than 2 values to unpack)
2016-11-09 11:45:14,511 ERROR [ckanext.harvest.queue] Import exception: need more than 2 values to unpack obj=0c7df1ac-2eb7-47dc-88b2-5ea0536c0422 guid=9d5a8a07-0cef-4733-9e1d-ccb35f582cf2 source=2b5ef920-c70a-4dfb-8826-1c17a0ddd97c
2016-11-09 11:45:14,511 ERROR [ckanext.harvest.queue] need more than 2 values to unpack
Traceback (most recent call last):
  File "/pops/src/ckanext-harvest/ckanext/harvest/queue.py", line 491, in fetch_and_import_stages
    success_import = harvester.import_stage(obj)
  File "/pops/src/ckanext-spatial/ckanext/spatial/harvesters/base.py", line 496, in import_stage
    is_valid, profile, errors = self._validate_document(harvest_object.content, harvest_object)
  File "/pops/src/ckanext-spatial/ckanext/spatial/harvesters/base.py", line 823, in _validate_document
    valid, profile, errors = validator.is_valid(xml)
ValueError: need more than 2 values to unpack
```

I tracked the problem down to the line

`xml = etree.fromstring(document_string)`

in ckanext-spatial/ckanext/spatial/harvesters/base.py in function _validate_document() on line 824. _document_string_ before transformation to XML appears that it contains all data, needed for harvesting, i.e.

```
<gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:srv="http://www.isotc211.org/2005/srv" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gml="http://www.opengis.net/gml" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:geonet="http://www.fao.org/geonetwork" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xsi:schemaLocation="http://www.isotc211.org/2005/gmd http://www.isotc211.org/2005/gmd/gmd.xsd http://www.isotc211.org/2005/gmx http://www.isotc211.org/2005/gmx/gmx.xsd http://www.isotc211.org/2005/srv http://schemas.opengis.net/iso/19139/20060504/srv/srv.xsd">
                <gmd:fileIdentifier>
                  <gco:CharacterString>9a744c8e-8628-4390-a16f-73d464985366</gco:CharacterString>
                </gmd:fileIdentifier>
                <gmd:language>
                  <gmd:LanguageCode codeList="http://www.loc.gov/standards/iso639-2/" codeListValue="slv"/>
                </gmd:language>
```

while after transformation to XML, resulting XML contains just this data:

`<Element {http://www.isotc211.org/2005/gmd}MD_Metadata at 0x5b877d0>`

Perhaps this is the source of the error, bad format of document_string, before it is converted to XML?

Anyway, I have checked in the code, and we seem to be using the right harvester, added from upstream's base.py: `<Plugin CSWHarvester 'csw_harvester'>`

Thank you,
Matevž

**Comment by davidread** [comment]
Sorry, I was in a rush yesterday, but sounds like it was no help.

I know this didn't trouble you, but for the sake of completeness for anyone else reading, to expand on what I said, it's these executables that need restarting after harvest code is changed:
```
sudo -u www-data /home/co/ckan/bin/paster --plugin=ckanext-harvest harvester gather_consumer --config=/var/ckan/ckan.ini
sudo -u www-data /home/co/ckan/bin/paster --plugin=ckanext-harvest harvester fetch_consumer --config=/var/ckan/ckan.ini
```
If you run them with supervisord then the simplest command is:

    sudo supervisorctl restart all

I'm always forgetting this step, which is why I thought that might be the problem. But that's great that you were doing this already.

--

Tracking down problems in harvests is not so easy when running them in celery, because you can only log - not print or use pdb. First I suggest to people to get it running on the command-line first like this:

    paster --plugin=ckanext-harvest harvester run_test my_harvester

--

The line with `xml = etree.fromstring(document_string)` is fine - it is converting the xml string to a nest of python objects. When you print it, it just shows the top one, but I'm pretty sure they are all there if you call its functions to iterate over its children, for example. You could do that in pdb.

--

The `ValueError: need more than 2 values to unpack` exception is related to the number of values returned by the is_valid() method. I'm now thinking It is not as easy to use CSWHarveser after all - it seems to use quite a lot of different code from SpatialHarvester, whereas GeminiCswHarvester has all its code in-line and I trust it.

I which case, I suggest you revert your ckan.plugins back to gemini_csw_harvester and just tell it to use the non-gemini validation. Your probably have:

    ckan.spatial.validator.profiles=iso19139eden,constraints-1.4,gemini2-1.3

in your ckan config. Change this to:

    ckan.spatial.validator.profiles=iso19139eden

or:

    ckan.spatial.validator.profiles=iso19139

and that should just do the iso validation and not the gemini ones. You may still see the word 'gemini' in the web interface where you choose a harvester, but this can be fixed in your fork by editing the strings returned by GeminiCswHarvester:info().

**Comment by zvetaM** [comment]
With the information from your last reply we have successfully harvested already 97 datasets; remaining errors seem to be solely due to differences between different iso19139 variations.

Thank you very much for your help, David!
